### ISSUE TITLE
Cannot export account data

### ISSUE THREAD

**Issue by tstephen** [omny-link/omny-link#70]
```
25901 2023-09-14 11:48:18.847  INFO 1 --- [io-8080-exec-10] l.o.c.r.CustomAccountRepository          : List accounts for tenant xxxx
25902 2023-09-14 11:48:19.454  INFO 1 --- [io-8080-exec-10] l.o.c.r.CustomAccountRepository          : Found ddd xxxx accounts in dddms
25903 2023-09-14 11:48:19.457 ERROR 1 --- [io-8080-exec-10] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dis      patcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.hibernate.LazyInitializ      ationException: failed to lazily initialize a collection of role: link.omny.custmgmt.model.Account.documents, could not initialize       proxy - no Session] with root cause
25904 ..LazyInitializationException: failed to lazily initialize a collection of role: link.omny.custmgmt.model.Account.documents, could       not initialize proxy - no Session
25905   at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.j      ava:606) ~[hibernate-core-5.4.28.Final.jar:5.4.28.Final]
25906   at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:      218) ~[hibernate-core-5.4.28.Final.jar:5.4.28.Final]
25907   at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:585) ~[hibernate-c      ore-5.4.28.Final.jar:5.4.28.Final]
25908   at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:149) ~[hibernate-core-5.      4.28.Final.jar:5.4.28.Final]
25909   at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:188) ~[hibernate-core-5.4.28.Final.jar:5.4.28.Fina      l]
25910   at link.omny.custmgmt.model.Account.getConsolidatedDocuments(Account.java:545) ~[custmgmt-3.1.7.jar:3.1.7]
25911   at link.omny.custmgmt.model.Account.toCsv(Account.java:516) ~[custmgmt-3.1.7.jar:3.1.7]
25912   at link.omny.custmgmt.web.AccountController.listForTenantAsCsv(AccountController.java:225) ~[custmgmt-3.1.7.jar:3.1.7]
```

**Comment by tstephen** [comment]
Resolved by PR 71
